version: "3.8"

services:
  #mongodb:
   # image: mongo:7
    #container_name: mongodb
    #ports:
     # - "27017:27017"
    #volumes:
     # - mongodb_data:/data/db
    #healthcheck:
     # test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      #interval: 10s
      #timeout: 5s
      #retries: 5
    #networks:
     # - my_network
    #restart: unless-stopped

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATIONMS: ${JWT_EXPIRATIONMS}
      SPRING_PROFILES_ACTIVE: dev
      # Faster file-change detection on Windows/WSL
      SPRING_DEVTOOLS_RESTART_POLL_INTERVAL: "2s"
      SPRING_DEVTOOLS_RESTART_QUIET_PERIOD: "1s"
      # Cloudinary
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    volumes:
      - ./Backend/commerce-api/commerce-api/src:/app/src
      - ./Backend/commerce-api/commerce-api/pom.xml:/app/pom.xml
      - maven_repo:/root/.m2
    #depends_on:
     # mongodb:
      #  condition: service_healthy
    networks:
      - my_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:5173"
    environment:
      VITE_API_BASE: /api
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "200"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - my_network
    restart: unless-stopped

volumes:
  mongodb_data:
  maven_repo:

networks:
  my_network:
    driver: bridge
